config/routes.rb
Rails.application.routes.draw do
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
  
  get 'posts/index'
  devise_for :users, controllers: { registrations: "registrations" }
  resources :users, only: [:index, :show] do
    resource :profile, only: [:show, :edit, :update] do
      member do
        post 'follow'
        delete 'unfollow'
      end
    end
  end

  resources :posts do
    resources :likes
    resources :comments
  end
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "posts#index"
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  validates_uniqueness_of :user_id
  validates :name, length: { minimum: 2, maximum: 20 }, allow_nil: true
  validates :bio, length: { maximum: 200 }

  validates :user_id, presence: true
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  include ProfilesHelper
  before_action :set_user

  def show
    @profile = @user.profile
  end

  def edit
    @profile = @user.profile
  end

  def update
    @profile = current_user.profile
    if @profile.update(profile_params)
      redirect_to user_profile_path(current_user), notice: 'Profile successfully updated.'
    else
      render 'edit', status: :unprocessable_entity
    end
  end

  def follow
    Relationship.create_or_find_by(follower_id: current_user.id, followed_id: @user.id)
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: [
          turbo_stream.replace(dom_id_for_follower(@user),
                               partial: '/profiles/follow_button',
                               locals: { user: @user }),
          turbo_stream.update("#{@user.id}-follower-count",
                              partial: '/profiles/follower_count',
                              locals: { user: @user })
        ]
      end
    end
  end

  def unfollow
    current_user.active_relationships.where(followed_id: @user.id).destroy_all
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: [
          turbo_stream.replace(dom_id_for_follower(@user),
                               partial: '/profiles/follow_button',
                               locals: { user: @user }),
          turbo_stream.update("#{@user.id}-follower-count",
                              partial: '/profiles/follower_count',
                              locals: { user: @user })
        ]
      end
    end
  end

  private

  def set_user
    @user = User.find(params[:user_id])
  end

  def profile_params
    params.require(:profile).permit(:name, :bio, :age, :location)
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
  include ActionView::RecordIdentifier

  def following?(user)
    current_user&.active_relationships&.exists?(followed_id: user.id)
  end

  def profile_gravatar(user, size: 80)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "http://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.profile.name, class: "profile-pic")
  end
  
  def dom_id_for_follower(follower)
    dom_id(follower)
  end
end

app/views/profiles/_follow_button.html.erb
<%= turbo_frame_tag(dom_id(user)) do %>
  <% if following?(user) %>
      <%= button_to 'Unfollow', unfollow_user_profile_path(user_id: user.id), method: :delete %>
    <% else %>
      <%= button_to 'Follow', follow_user_profile_path(user_id: user.id), method: :post %>
  <% end %>
<% end %>

app/views/profiles/_follower_count.html.erb
<%= turbo_frame_tag "#{user.id}-follower-count" do  %>
  <div>
    <%= pluralize(user.passive_relationships.count, "follower") %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<div>
  <%= link_to 'Change your profile picture via Gravatar (opens in new tab)', 'https://www.gravatar.com/profile', target: "_blank", class: "gravatar-link" %>
</div>

<h1>Edit @<%= current_user.username %>'s Profile</h1>

<%= form_with(model: @profile, url: user_profile_path(current_user), class: "profile-form") do |form| %>
  <div class="form-group">
    <%= form.label :name, class: "form-label" %>
    <%= form.text_field :name, class: "form-input" %>
  </div>

  <div class="form-group">
    <%= form.label :bio, class: "form-label" %>
    <%= form.text_area :bio, class: "form-input" %>
  </div>

  <div class="form-group">
    <%= form.label :age, class: "form-label" %>
    <%= form.number_field :age, within: 13...120, class: "form-input" %>
  </div>

  <div class="form-group">
    <%= form.label :location, class: "form-label" %>
    <%= form.text_field :location, class: "form-input" %>
  </div>

  <div>
    <%= form.submit "Save Changes", class: "submit-button" %>
  </div>
<% end %>

app/views/profiles/show.html.erb
<% if @user == current_user %>
  <div class="profile-actions">
    <%= link_to "Edit Profile", edit_user_profile_path(current_user), class: "button-link" %>
    <%= button_to "New Post", new_post_path, method: :get, class: "btn btn-primary" %> 
  </div>
<% elsif current_user %>
  <%= render 'follow_button', user: @user %>
<% end %>

<div class="profile-header">
  <%= profile_gravatar @user %>
  <h1><%= @profile.name %></h1>
  <p>@<%= @user.username %></p>
  <p><%= @profile.bio %></p>
</div>

<div class="profile-stats">
  <%= render 'follower_count', user: @user %>
  <div><%= @user.active_relationships.count %> Following</div>
  <p>Age: <%= @profile.age %></p>
  <p>Location: <%= @profile.location %></p>
</div>

<div class="profile-posts">
  <h3>Posts:</h3>
  <% @user.posts.all.reverse_order.each do |post| %>
    <div class="post">
      <p><%= post.content %></p>
      <p><%= link_to post.updated_at.strftime("%m/%d/%Y %I:%M%p"), post_path(post) %></p>
      <% if post.user_id == current_user.id %>
        <%= button_to 'Delete Post', post_path(post), method: :delete, class: "delete-post-button" %>
      <% end %>

      <div class="post-likes">
        <%= pluralize(post.likes.count, 'Like') %>
        <% already_liked = post.likes.find { |like| like.user_id == current_user.id } %>
        <% if already_liked %>
          <%= button_to 'Unlike', post_like_path(post, already_liked, source_view: 'index'), method: :delete, class: "like-button" %>
        <% else %>
          <%= button_to 'Like', post_likes_path(post, source_view: 'index'), method: :post, class: "like-button" %>
        <% end %>
      </div>

      <div class="post-comments">
        <%= render "posts/comment_form", post: post, source_view: 'index' %>
        <div class="post-comments-comments">
          <h4>Comments:</h4>
          <%= render "posts/comments", post: post %>
        </div>
      </div>
    </div>
    <hr>
  <% end %>
</div>