config/routes.rb
Rails.application.routes.draw do
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
  
  get 'posts/index'
  devise_for :users, controllers: { registrations: "registrations" }
  resources :users, only: [:index, :show] do
    resource :profile, only: [:show, :edit, :update] do
      member do
        post 'follow'
        delete 'unfollow'
      end
    end
  end

  resources :posts do
    resources :likes
    resources :comments
  end
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "posts#index"
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy

  validates :content, length: { maximum: 240 }

  scope :from_users_followed_by, -> (user) do
    followed_user_ids = "SELECT followed_id FROM relationships WHERE follower_id = :user_id"
    where("user_id IN (#{followed_user_ids}) OR user_id = :user_id", user_id: user.id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
    @comments = Comment.where(post_id: @post.id)
    @comment = @post.comments.build
  end

  def new
    @post = current_user.posts.new
  end

  def create
    @post = current_user.posts.new(post_params)

    if @post.save
      redirect_to @post
    else
      puts @post.errors.full_messages
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(post_params)
      redirect_to post_path, notice: 'Post successfully updated.'
    else
      render 'edit', status: :unprocessable_entity
    end
  end

  def destroy
    @post = Post.find(params[:id])
    if @post.user_id == current_user.id
      @post.destroy
    end
    redirect_to root_path, status: :see_other
  end

  private

  def post_params
    params.require(:post).permit(:content)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_comment_form.html.erb
<div class="comment-form">
  <%= form_with model: [post, post.comments.build] do |form| %>
    <div class="form-group">
      <%= form.label :content, 'Comment:' %>
      <%= form.text_area :content, class: 'form-control' %>
    </div>

    <div class="form-actions">
      <%= form.submit 'Post Comment', class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>

app/views/posts/_comments.html.erb
<div class="comments-section">
  <% post.comments.reject(&:new_record?).each do |comment| %>
    <div class="comment">
      <div class="comment-header">
        <span class="comment-avatar"><%= profile_gravatar comment.user %></span>
        <span class="comment-author">
          <%= link_to "@#{comment.user.username}", user_profile_path(comment.user) %>
        </span>
      </div>
      
      <div class="comment-body">
        <p class="comment-content"><%= comment.content %></p>
        <p class="comment-timestamp"><%= time_ago_in_words(comment.created_at) %> ago</p>
      </div>
      
      <% if comment.user_id == current_user.id %>
        <div class="comment-actions">
          <%= button_to 'Delete', post_comment_path(post, comment), method: :delete, class: 'btn btn-delete' %>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/posts/_form.html.erb
<%= turbo_frame_tag @post do %>
  <article class="post-form">
    <header class="form-header">
      <%= profile_gravatar @post.user %>
    </header>

    <%= form_with(model: @post, class: 'form-container') do |form| %>
      <div class="form-group">
        <%= form.label :content, "What's on your mind?", class: 'form-label' %>
        <%= form.text_area :content, class: 'form-input', maxlength: 240, placeholder: 'Write your post here...' %>
        <p class="form-hint">Max: 240 characters</p>
      </div>

      <div class="form-actions">
        <%= form.submit 'Post', class: 'form-submit' %>
      </div>
    <% end %>
  </article>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= render "form" %>

app/views/posts/index.html.erb
<h1>Dashboard</h1>

<div class="new-post-button">
  <%= button_to "New Post", new_post_path, method: :get, class: "btn btn-primary" %> 
</div>

<% @posts = Post.from_users_followed_by(current_user) %>
<% @posts.reverse_order.each do |post| %>
  <article class="post">
    <header class="post-header">
      <%= profile_gravatar post.user %>
      <%= link_to "@#{post.user.username}", user_profile_path(post.user) %>
    </header>

    <section class="post-content">
      <p><%= post.content %></p>
      <p><%= link_to post.updated_at.strftime("%m/%d/%Y %I:%M%p"), post_path(post) %></p>
      <% if post.user_id == current_user.id %>
        <%= button_to 'Delete Post', post_path(post), method: :delete, class: 'delete-post-btn' %>
      <% end %>
    </section>

    <section class="post-likes">
      <p><%= pluralize(post.likes.count, 'Like') %></p>
      <% already_liked = post.likes.find { |like| like.user_id == current_user.id} %>
      <% if already_liked %>
        <%= button_to 'Unlike', post_like_path(post, already_liked, source_view: 'index'), method: :delete, class: 'like-btn' %>
      <% else %>
        <%= button_to 'Like', post_likes_path(post, source_view: 'index'), method: :post, class: 'like-btn' %>
      <% end %>
    </section>

    <section class="comments-section">
      <%= render "comment_form", post: post, source_view: 'index' %>
      <h4>Comments:</h4>
      <%= render "comments", post: post %>
    </section>
  </article>
<% end %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render "form" %>

app/views/posts/show.html.erb
<article class="user-post">
  <header>
    <h4>
      <%= profile_gravatar @post.user %>
      <%= link_to "@#{@post.user.username}", user_profile_path(@post.user) %>
    </h4>
  </header>

  <section>
    <p><%= @post.content %></p>
    <p><%= @post.updated_at.strftime("%m/%d/%Y %I:%M%p") %></p>
  </section>

  <section>
    <% if @post.user_id == current_user.id %>
      <div>
        <%= button_to "Edit Post", edit_post_path, method: :get %>
        <%= button_to "Delete Post", post_path(@post), method: :delete %>
      </div>
    <% end %>
  </section>

  <section>
    <p>
      <%= link_to "#{pluralize(@post.likes.count, 'Like')}", post_likes_path(@post) %>
    </p>
    <% already_liked = @post.likes.find { |like| like.user_id == current_user.id } %>
    <% if already_liked %>
      <%= button_to "Unlike", post_like_path(@post, already_liked), method: :delete %>
    <% else %>
      <%= button_to "Like", post_likes_path(@post), method: :post %>
    <% end %>
  </section>

  <section>
    <h4>Comments:</h4>
    <%= render "comment_form", post: @post, source_view: 'show' %>
    <%= render "comments", post: @post %>
  </section>
</article>