config/routes.rb
Rails.application.routes.draw do
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
  
  get 'posts/index'
  devise_for :users, controllers: { registrations: "registrations" }
  resources :users, only: [:index, :show] do
    resource :profile, only: [:show, :edit, :update] do
      member do
        post 'follow'
        delete 'unfollow'
      end
    end
  end

  resources :posts do
    resources :likes
    resources :comments
  end
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "posts#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Frendo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

    <% if flash[:notice] || flash[:alert] %>
      <div class="flash-messages">
        <% if flash[:notice] %>
          <p class="notice"><%= flash[:notice] %></p>
        <% end %>
        <% if flash[:alert] %>
          <p class="alert"><%= flash[:alert] %></p>
        <% end %>
      </div>
    <% end %>

    <header>
      <div class="nav">
        <div>
          <%= link_to 'Home', root_path %>

          <% if user_signed_in? %>

            <%= link_to "Profile", user_profile_path(current_user) %>
            <%= link_to "Users", users_path %>
        </div>

        <div>
            <%= button_to "Log out", destroy_user_session_path, method: :delete %>
        </div>

        <% else %>
          <%= link_to "Login", new_user_session_path %> 
          <%= link_to "Sign Up", new_user_registration_path %> 
        <% end %>
      </div>
    </header>


   <main class="main-content">
      <%= yield %>
    </main>

  </body>
</html>